Bugfixes & Improvments
Merubokkusu/discord-spam-bots pull request #80
Opened 2021-02-09 08:22 UTC by DanielRTRD

2021-02-09 21:35 UTC, Merubokkusu reviewed
The old join server is still used for email:pass methods.

2021-02-10 11:26 UTC, xyzzzzzzzzzzzzzz requested changes
Yeah I think this updated code would work with the account creator. Since you are using their newer API. The main error people found with it was "list index out of range" but we'll see. I'll propose a merge later on today.

2021-02-10 23:11 UTC, Merubokkusu approved these changes

2021-02-10 23:15 UTC, Merubokkusu commented
Everything is great besides 4cb6035

2021-02-10 23:17 UTC, merged